export type { CommunicationType, CommunicationStatus, CommunicationTemplateKey, CommunicationResult, SMSProvider, WhatsAppProvider, EmailProvider, CommunicationLogEntry, TemplateVariables } from "./types"
export type { CommunicationTemplate, TemplateChannel } from "./templates"
export { COMMUNICATION_TEMPLATES, getDefaultTemplate, renderTemplate, sanitizeTemplate } from "./templates"
export { sendCommunication, sendSMSDirect, sendWhatsAppDirect, sendEmailDirect } from "./sender"
export { getSMSProvider, resetSMSProvider } from "./sms"
export { getWhatsAppProvider, resetWhatsAppProvider } from "./whatsapp"
export { getEmailProvider, resetEmailProvider } from "./email"
export { checkRateLimit, recordAttempt, clearRateLimit } from "./rate-limit"
export { processAppointmentReminders, processMaintenanceReminders } from "./scheduler"