import { ImageResponse } from "next/og"

const PRIMARY_LIGHT_SVG_BASE64 =
  "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgICAgd2lkdGg9IjEwODciIGhlaWdodD0iMjExIgogICAgIHZpZXdCb3g9IjAgMCAxMDg3IDIxMSIKICAgICByb2xlPSJpbWciIGFyaWEtbGFiZWxsZWRieT0idGl0bGUiPgogIDx0aXRsZSBpZD0idGl0bGUiPkJha2ltWCBIb3Jpem9udGFsIExvZ28gTGlnaHQ8L3RpdGxlPgogIDxkZWZzPgogICAgCjxsaW5lYXJHcmFkaWVudCBpZD0ibmF2eSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+CiAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzA3MUY0OSIvPgogIDxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzAzMTQzMiIvPgo8L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9ImJsdWUiIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMTAwJSIgeTI9IjEwMCUiPgogIDxzdG9wIG9mZnNldD0iMCUiIHN0b3AtY29sb3I9IiMyRjg0RkYiLz4KICA8c3RvcCBvZmZzZXQ9IjU1JSIgc3RvcC1jb2xvcj0iIzA4NjVFOCIvPgogIDxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzA2NEJCRiIvPgo8L2xpbmVhckdyYWRpZW50PgoKICA8L2RlZnM+CiAgCjxwYXRoIGQ9Ik0gNjIuMDAsMTgyLjAwIEwgNjMuMDAsMTgzLjAwIEwgNzAuMDAsMTgzLjAwIEwgNzEuMDAsMTgyLjAwIEwgNzYuMDAsMTgzLjAwIEwgNzguMDAsMTgyLjAwIEwgMTI0LjAwLDE4Mi4wMCBMIDEyNS4wMCwxODMuMDAgTCAxOTMuMDAsMTgyLjAwIEwgMjA3LjAwLDE2Ny4wMCBMIDIwNy4wMCwxNjQuMDAgTCAyMDUuMDAsMTU5LjAwIEwgMjAyLjAwLDE1Ni4wMCBMIDE5NC4wMCwxNTIuMDAgTCAxNzcuMDAsMTQ4LjAwIEwgMTUzLjAwLDE0Ni4wMCBMIDEzMy4wMCwxMzMuMDAgTCAxMjEuMDAsMTI4LjAwIEwgMTAyLjAwLDEyNy4wMCBMIDEwMS4wMCwxMjYuMDAgTCAxMDAuMDAsMTI3LjAwIEwgODkuMDAsMTI3LjAwIFogTSA5MC4wMCwxNTYuMDAgTCA5MS4wMCwxNTUuMDAgTCAxMDAuMDAsMTU1LjAwIEwgMTAxLjAwLDE1Ni4wMCBMIDEyNS4wMCwxNTcuMDAgTCAxMzkuMDAsMTYwLjAwIEwgMTU0LjAwLDE2Ni4wMCBMIDE1NS4wMCwxNjMuMDAgTCAxNjAuMDAsMTU4LjAwIEwgMTY2LjAwLDE1NS4wMCBMIDE3Ny4wMCwxNTUuMDAgTCAxODIuMDAsMTU3LjAwIEwgMTg4LjAwLDE2My4wMCBMIDE5MC4wMCwxNjcuMDAgTCAxOTAuMDAsMTczLjAwIEwgMTg5LjAwLDE3NC4wMCBMIDE4Ny4wMCwxNzMuMDAgTCAxODYuMDAsMTY4LjAwIEwgMTgxLjAwLDE2My4wMCBMIDE3Ny4wMCwxNjEuMDAgTCAxNjguMDAsMTYxLjAwIEwgMTYxLjAwLDE2Ni4wMCBMIDE1OC4wMCwxNzIuMDAgTCAxNTcuMDAsMTc5LjAwIEwgMTU0LjAwLDE4MC4wMCBMIDE0OS4wMCwxNzQuMDAgTCAxMzIuMDAsMTY1LjAwIEwgMTExLjAwLDE2MC4wMCBMIDkxLjAwLDE1OC4wMCBaIE0gOTkuMDAsMTMyLjAwIEwgMTAwLjAwLDEzMS4wMCBMIDExNS4wMCwxMzEuMDAgTCAxMjQuMDAsMTMzLjAwIEwgMTM1LjAwLDEzOC4wMCBMIDE0Mi4wMCwxNDMuMDAgTCAxNDQuMDAsMTQ2LjAwIEwgMTQzLjAwLDE0Ny4wMCBMIDEzNC4wMCwxNDcuMDAgTCAxMzMuMDAsMTQ2LjAwIEwgMTA5LjAwLDE0NS4wMCBMIDEwMy4wMCwxNDEuMDAgWiBNIDc4NC4wMCw3OC4wMCBMIDc4NC4wMCwxNjYuMDAgTCA4MDcuMDAsMTY2LjAwIEwgODA3LjAwLDk5LjAwIEwgODA4LjAwLDk4LjAwIEwgODM2LjAwLDk4LjAwIEwgODM5LjAwLDEwMS4wMCBMIDg0MC4wMCwxMDQuMDAgTCA4NDAuMDAsMTYyLjAwIEwgODM5LjAwLDE2NS4wMCBMIDg0MC4wMCwxNjYuMDAgTCA4NjIuMDAsMTY2LjAwIEwgODYzLjAwLDE2NS4wMCBMIDg2My4wMCw5OS4wMCBMIDg2NC4wMCw5OC4wMCBMIDg4NS4wMCw5OC4wMCBMIDg5Mi4wMCwxMDIuMDAgTCA4OTUuMDAsMTA4LjAwIEwgODk1LjAwLDE2NS4wMCBMIDg5Ni4wMCwxNjYuMDAgTCA5MTguMDAsMTY2LjAwIEwgOTE5LjAwLDE2NS4wMCBMIDkxOS4wMCwxMTAuMDAgTCA5MTguMDAsMTA5LjAwIEwgOTE4LjAwLDEwMi4wMCBMIDkxNC4wMCw5Mi4wMCBMIDkwMy4wMCw4Mi4wMCBMIDg4OS4wMCw3OC4wMCBaIE0gNzQ0LjAwLDc4LjAwIEwgNzQzLjAwLDc5LjAwIEwgNzQzLjAwLDE2NS4wMCBMIDc0NC4wMCwxNjYuMDAgTCA3NjYuMDAsMTY2LjAwIEwgNzY2LjAwLDc4LjAwIFogTSA1MTkuMDAsNzguMDAgTCA1MTkuMDAsOTcuMDAgTCA1MjAuMDAsOTguMDAgTCA1ODMuMDAsOTguMDAgTCA1ODYuMDAsOTkuMDAgTCA1OTAuMDAsMTA0LjAwIEwgNTkwLjAwLDExMi4wMCBMIDU4OS4wMCwxMTMuMDAgTCA1MzIuMDAsMTEzLjAwIEwgNTIxLjAwLDExNy4wMCBMIDUxNS4wMCwxMjMuMDAgTCA1MTEuMDAsMTM1LjAwIEwgNTEyLjAwLDE0OS4wMCBMIDUxOS4wMCwxNjAuMDAgTCA1MjYuMDAsMTY0LjAwIEwgNTM0LjAwLDE2Ni4wMCBMIDYxMy4wMCwxNjYuMDAgTCA2MTMuMDAsMTAwLjAwIEwgNjEwLjAwLDkxLjAwIEwgNjA0LjAwLDg0LjAwIEwgNTk5LjAwLDgxLjAwIEwgNTg4LjAwLDc4LjAwIFogTSA1MzQuMDAsMTM4LjAwIEwgNTM1LjAwLDEzNS4wMCBMIDU0MC4wMCwxMzEuMDAgTCA1ODkuMDAsMTMxLjAwIEwgNTkwLjAwLDEzMi4wMCBMIDU5MC4wMCwxNDYuMDAgTCA1ODkuMDAsMTQ3LjAwIEwgNTQwLjAwLDE0Ny4wMCBMIDUzNS4wMCwxNDMuMDAgWiBNIDM3NC4wMCw1MS4wMCBMIDM3NC4wMCwxNjUuMDAgTCAzNzUuMDAsMTY2LjAwIEwgNDYzLjAwLDE2Ni4wMCBMIDQ3OC4wMCwxNjMuMDAgTCA0ODcuMDAsMTU4LjAwIEwgNDkyLjAwLDE1My4wMCBMIDQ5OC4wMCwxNDEuMDAgTCA0OTkuMDAsMTM0LjAwIEwgNDk4LjAwLDEyNC4wMCBMIDQ5NC4wMCwxMTUuMDAgTCA0ODQuMDAsMTA1LjAwIEwgNDkwLjAwLDEwMC4wMCBMIDQ5My4wMCw5NC4wMCBMIDQ5NS4wMCw4MC4wMCBMIDQ5MS4wMCw2Ni4wMCBMIDQ4My4wMCw1Ny4wMCBMIDQ3Ni4wMCw1My4wMCBMIDQ2NC4wMCw1MC4wMCBMIDM3NS4wMCw1MC4wMCBaIE0gMzk4LjAwLDExOS4wMCBMIDM5OS4wMCwxMTguMDAgTCA0NjEuMDAsMTE4LjAwIEwgNDY3LjAwLDEyMC4wMCBMIDQ3Mi4wMCwxMjUuMDAgTCA0NzQuMDAsMTMzLjAwIEwgNDcyLjAwLDEzOC4wMCBMIDQ2My4wMCwxNDQuMDAgTCAzOTkuMDAsMTQ0LjAwIEwgMzk4LjAwLDE0My4wMCBaIE0gMzk4LjAwLDczLjAwIEwgMzk5LjAwLDcyLjAwIEwgNDU5LjAwLDcyLjAwIEwgNDY1LjAwLDc0LjAwIEwgNDY5LjAwLDc4LjAwIEwgNDcwLjAwLDg5LjAwIEwgNDY1LjAwLDk1LjAwIEwgNDYwLjAwLDk3LjAwIEwgMzk5LjAwLDk3LjAwIEwgMzk4LjAwLDk2LjAwIFogTSA2MzEuMDAsNDIuMDAgTCA2MzEuMDAsMTY2LjAwIEwgNjUzLjAwLDE2Ni4wMCBMIDY1NC4wMCwxNjUuMDAgTCA2NTQuMDAsMTI2LjAwIEwgNjU1LjAwLDEyNS4wMCBMIDY2Ni4wMCwxMzQuMDAgTCA2OTguMDAsMTY2LjAwIEwgNzMxLjAwLDE2Ni4wMCBMIDY4NS4wMCwxMjEuMDAgTCA3MDAuMDAsMTA1LjAwIEwgNzI5LjAwLDc4LjAwIEwgNjk2LjAwLDc4LjAwIEwgNjU1LjAwLDExNy4wMCBMIDY1NC4wMCwxMTYuMDAgTCA2NTQuMDAsNDIuMDAgWiBNIDEwMC4wMCw1LjAwIEwgODUuMDAsNDQuMDAgTCA4NS4wMCw0Ny4wMCBMIDIxNS4wMCw0Ny4wMCBMIDIyMi4wMCw1My4wMCBMIDIyMy4wMCw1OC4wMCBMIDIyMS4wMCw2NC4wMCBMIDIxNS4wMCw3MC4wMCBMIDIxMC4wMCw3Mi4wMCBMIDExOC4wMCw3Mi4wMCBMIDExNC4wMCw3OC4wMCBMIDk5LjAwLDExMi4wMCBMIDE4Ny4wMCwxMTIuMDAgTCAxOTIuMDAsMTEzLjAwIEwgMjAzLjAwLDExOC4wMCBMIDIyNy4wMCwxNDUuMDAgTCAyNTEuMDAsMTE4LjAwIEwgMjM1LjAwLDk4LjAwIEwgMjM1LjAwLDk2LjAwIEwgMjUzLjAwLDg0LjAwIEwgMjYxLjAwLDc0LjAwIEwgMjY3LjAwLDYwLjAwIEwgMjY4LjAwLDQyLjAwIEwgMjY2LjAwLDM0LjAwIEwgMjYwLjAwLDIzLjAwIEwgMjQ4LjAwLDEyLjAwIEwgMjQwLjAwLDguMDAgTCAyMjkuMDAsNS4wMCBaIiBmaWxsPSJ1cmwoI25hdnkpIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz4KPHBhdGggZD0iTSAyMS4wMCwxNTAuMDAgTCA1Ni4wMCwxNTAuMDAgTCA1OS4wMCwxNDguMDAgTCA2NC4wMCwxMzYuMDAgTCAzMC4wMCwxMzYuMDAgTCAyNS4wMCwxNDAuMDAgWiBNIDMyMC4wMCwyMDUuMDAgTCAyNTYuMDAsMTMxLjAwIEwgMTg5LjAwLDIwNS4wMCBMIDIyOC4wMCwyMDUuMDAgTCAyNTQuMDAsMTc4LjAwIEwgMjYwLjAwLDE4My4wMCBMIDI3OS4wMCwyMDUuMDAgWiBNIDEwMTguMDAsMTM4LjAwIEwgMTAxOC4wMCwxNDAuMDAgTCAxMDU3LjAwLDE3OC4wMCBMIDEwODYuMDAsMTc4LjAwIEwgMTA4Ni4wMCwxNjEuMDAgTCAxMDQwLjAwLDExNi4wMCBaIE0gNS4wMCwxMTYuMDAgTCA3NS4wMCwxMTYuMDAgTCA4MC4wMCwxMTMuMDAgTCA4NS4wMCwxMDEuMDAgTCAxNC4wMCwxMDEuMDAgTCA4LjAwLDEwNy4wMCBaIE0gMzI2LjAwLDk5LjAwIEwgMjkwLjAwLDk5LjAwIEwgMjY2LjAwLDEyNS4wMCBMIDI4MS4wMCwxNDQuMDAgTCAyODQuMDAsMTQ2LjAwIEwgMzI3LjAwLDEwMC4wMCBaIE0gMzEuMDAsODEuMDAgTCAzMy4wMCw4Mi4wMCBMIDkwLjAwLDgxLjAwIEwgOTQuMDAsNzguMDAgTCA5OS4wMCw2OC4wMCBMIDk4LjAwLDY3LjAwIEwgNDEuMDAsNjcuMDAgTCAzNi4wMCw3MC4wMCBaIE0gOTIxLjAwLDQ0LjAwIEwgOTg4LjAwLDExMS4wMCBMIDkwOS4wMCwxOTEuMDAgTCA5NTQuMDAsMTkxLjAwIEwgMTAzMy4wMCwxMDkuMDAgTCA5NjguMDAsNDQuMDAgWiBNIDc0NS4wMCw0NC4wMCBMIDc0NC4wMCw0NS4wMCBMIDc0NC4wMCw2NS4wMCBMIDc0Ni4wMCw2Ni4wMCBMIDc0Ny4wMCw2NS4wMCBMIDc2NS4wMCw2NS4wMCBMIDc2Ni4wMCw2NC4wMCBMIDc2Ni4wMCw0NS4wMCBMIDc2NS4wMCw0NC4wMCBaIE0gMTA4Ni4wMCwyNy4wMCBMIDEwNjcuMDAsMjcuMDAgTCAxMDE4LjAwLDc5LjAwIEwgMTA0MC4wMCwxMDIuMDAgTCAxMDg2LjAwLDU0LjAwIFoiIGZpbGw9InVybCgjYmx1ZSkiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPgoKPC9zdmc+Cg=="

const logoDataUrl = `data:image/svg+xml;base64,${PRIMARY_LIGHT_SVG_BASE64}`

export const alt = "BakimX — Oto Servis Yönetim Platformu"
export const size = { width: 1200, height: 630 }
export const contentType = "image/png"

export default function OpenGraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "linear-gradient(135deg, #0B1F3A 0%, #102A43 100%)",
          padding: 80,
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 40,
          }}
        >
          <img
            src={logoDataUrl}
            width={560}
            height={109}
            style={{ objectFit: "contain" }}
            alt="BakimX"
          />
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 12,
          }}
        >
          <div
            style={{
              width: 48,
              height: 3,
              background: "#38BDF8",
              borderRadius: 9999,
            }}
          />
          <p
            style={{
              color: "#CBD5E1",
              fontSize: 32,
              fontWeight: 500,
              letterSpacing: 0.5,
              margin: 0,
            }}
          >
            Oto Servis Yönetim Platformu
          </p>
          <div
            style={{
              width: 48,
              height: 3,
              background: "#38BDF8",
              borderRadius: 9999,
            }}
          />
        </div>
      </div>
    ),
    { ...size },
  )
}